name = "dify-tools-worker"
compatibility_date = "2025-03-14"

[vars]
TOKEN = "zctdify2025asd123"
OPENAPI_VERSION = "3.1.0"
TOOL_VERSION = "1.0.0"
TOOL_NAME = "Dify Custom Tool"
TOOL_DESCRIPTION = "Dify Custom Tool"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "dify"
database_id = "75b55c0d-5b0d-4b7f-8b5d-8cdd460b6280"
